excluded:
 - build/SwiftLift.build/Release-iphoneos/SwiftLift.build/DerivedSources/GeneratedAssetSymbols.swift

disabled_rules:
  - multiple_closures_with_trailing_closure

line_length: 130

file_length:
  warning: 1000
  error: 1500

function_body_length:
  warning: 100
  error: 200

cyclomatic_complexity:
  warning: 15
  error: 20

type_body_length:
  warning: 350
  error: 500
