name: Update Version

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  update_version:
    runs-on: macos-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all branches
        run: |
          git fetch --prune
          git fetch origin develop:develop

      - name: Checkout the correct branch
        run: |
          git checkout ${{ github.event.pull_request.head.ref }}

      - name: Validate version format
        run: |
          version="${{ github.event.pull_request.title }}"
          if ! [[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version format. Version should be in the format X.Y.Z (e.g., 1.2.3)."
            exit 1
          fi
          echo "Version format is valid: $version"

      - name: Update CFBundleShortVersionString in Info.plist
        run: |
          plist_path="SwiftLift/Info.plist"
          new_version="${{ github.event.pull_request.title }}"
          /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string $new_version" "$plist_path" || \
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $new_version" "$plist_path"
          /usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$plist_path"
          
      - name: Manually update MARKETING_VERSION in project.pbxproj
        run: |
          new_version="0.0.3"
          pbxproj_file="SwiftLift.xcodeproj/project.pbxproj"
          # Replace the existing MARKETING_VERSION with the new version
          sed -i '' "s/MARKETING_VERSION = [0-9.]*/MARKETING_VERSION = $new_version/g" "$pbxproj_file"          
          # Verify the change
          grep "MARKETING_VERSION" "$pbxproj_file"

      - name: Commit changes
        run: |
          new_version="${{ github.event.pull_request.title }}"
          echo "New Version: $new_version"
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add SwiftLift/Info.plist
          git add SwiftLift.xcodeproj/project.pbxproj  # Ensure Xcode changes are committed
          git commit -m "Update version to $new_version [ci skip]"
          git push origin ${{ github.event.pull_request.head.ref }}
